SEARCH_CONFIG = {
    "negative_terms": "-job -jobs -hiring -careers -vacancy -recruitment",
    # Companies keyed by exact NSE ticker symbols
    "companies": {
        "RELIANCE": {"aliases": ["Reliance Industries Ltd"]},
        "HDFCBANK": {"aliases": ["HDFC Bank Ltd"]},
        "ICICIBANK": {"aliases": ["ICICI Bank Ltd"]},
        "INFY": {"aliases": ["Infosys Ltd"]},
        "SBIN": {"aliases": ["State Bank of India"]},
        "TCS": {"aliases": ["Tata Consultancy Services Ltd"]},
        "BHARTIARTL": {"aliases": ["Bharti Airtel Ltd"]},
        "ITC": {"aliases": ["ITC Ltd"]},
        "LT": {"aliases": ["Larsen & Toubro Ltd"]},
        "KOTAKBANK": {"aliases": ["Kotak Mahindra Bank Ltd"]},
        "HINDUNILVR": {"aliases": ["Hindustan Unilever Ltd"]},
        "AXISBANK": {"aliases": ["Axis Bank Ltd"]},
        "BAJFINANCE": {"aliases": ["Bajaj Finance Ltd"]},
        "ADANIENT": {"aliases": ["Adani Enterprises Ltd"]},
        "ADANIPORTS": {"aliases": ["Adani Ports and SEZ Ltd"]},
        "SUNPHARMA": {"aliases": ["Sun Pharmaceutical Industries Ltd"]},
        "MARUTI": {"aliases": ["Maruti Suzuki India Ltd"]},
        "M&M": {"aliases": ["Mahindra & Mahindra Ltd"]},
        "ULTRACEMCO": {"aliases": ["UltraTech Cement Ltd"]},
        "TATASTEEL": {"aliases": ["Tata Steel Ltd"]},
        "NESTLEIND": {"aliases": ["Nestle India Ltd"]},
        "WIPRO": {"aliases": ["Wipro Ltd"]},
        "TECHM": {"aliases": ["Tech Mahindra Ltd"]},
        "JSWSTEEL": {"aliases": ["JSW Steel Ltd"]},
        "POWERGRID": {"aliases": ["Power Grid Corporation of India Ltd"]},
        "NTPC": {"aliases": ["NTPC Ltd"]},
        "COALINDIA": {"aliases": ["Coal India Ltd"]},
        "TATAMOTORS": {"aliases": ["Tata Motors Ltd"]},
        "TATACONSUM": {"aliases": ["Tata Consumer Products Ltd"]},
        "GRASIM": {"aliases": ["Grasim Industries Ltd"]},
        "BAJAJFINSV": {"aliases": ["Bajaj Finserv Ltd"]},
        "HCLTECH": {"aliases": ["HCL Technologies Ltd"]},
        "ASIANPAINT": {"aliases": ["Asian Paints Ltd"]},
        "HDFCLIFE": {"aliases": ["HDFC Life Insurance Company Ltd"]},
        "SBILIFE": {"aliases": ["SBI Life Insurance Company Ltd"]},
        "DIVISLAB": {"aliases": ["Divi's Laboratories Ltd"]},
        "CIPLA": {"aliases": ["Cipla Ltd"]},
        "DRREDDY": {"aliases": ["Dr. Reddy's Laboratories Ltd"]},
        "TITAN": {"aliases": ["Titan Company Ltd"]},
        "BRITANNIA": {"aliases": ["Britannia Industries Ltd"]},
        "EICHERMOT": {"aliases": ["Eicher Motors Ltd"]},
        "TATAPOWER": {"aliases": ["Tata Power Company Ltd"]},
        "IOC": {"aliases": ["Indian Oil Corporation Ltd"]},
        "HINDALCO": {"aliases": ["Hindalco Industries Ltd"]},
        "UPL": {"aliases": ["UPL Ltd"]},
        "SHREECEM": {"aliases": ["Shree Cement Ltd"]},
        "BPCL": {"aliases": ["Bharat Petroleum Corporation Ltd"]},
        "HEROMOTOCO": {"aliases": ["Hero MotoCorp Ltd"]},
        "ONGC": {"aliases": ["ONGC Ltd"]},
        "ZOMATO": {"aliases": ["Zomato Ltd"]},
        "ADANIGREEN": {"aliases": ["Adani Green Energy Ltd"]},
        "ADANIENSOL": {"aliases": ["Adani Energy Solutions", "Adani Transmission Ltd"]},
        "AMBUJACEM": {"aliases": ["Ambuja Cements Ltd"]},
        "DABUR": {"aliases": ["Dabur India Ltd"]},
        "PIDILITIND": {"aliases": ["Pidilite Industries Ltd"]},
        "SBICARD": {"aliases": ["SBI Cards and Payment Services Ltd"]},
        "ICICIGI": {"aliases": ["ICICI Lombard General Insurance Ltd"]},
        "ICICIPRULI": {"aliases": ["ICICI Prudential Life Insurance Ltd"]},
        "DLF": {"aliases": ["DLF Ltd"]},
        "HAVELLS": {"aliases": ["Havells India Ltd"]},
        "BERGEPAINT": {"aliases": ["Berger Paints India Ltd"]},
        "GODREJCP": {"aliases": ["Godrej Consumer Products Ltd"]},
        "COLPAL": {"aliases": ["Colgate Palmolive Ltd"]},
        "CHOLAFIN": {"aliases": ["Cholamandalam Investment and Finance"]},
        "BANKBARODA": {"aliases": ["Bank of Baroda"]},
        "GAIL": {"aliases": ["GAIL (India) Ltd"]},
        "VEDL": {"aliases": ["Vedanta Ltd"]},
        "NMDC": {"aliases": ["NMDC Ltd"]},
        "INDUSINDBK": {"aliases": ["IndusInd Bank Ltd"]},
        "TORNTPHARM": {"aliases": ["Torrent Pharma Ltd"]},
        "MPHASIS": {"aliases": ["Mphasis Ltd"]},
        "LUPIN": {"aliases": ["Lupin Ltd"]},
        "SIEMENS": {"aliases": ["Siemens Ltd"]},
        "ABB": {"aliases": ["ABB India Ltd"]},
        "SRF": {"aliases": ["SRF Ltd"]},
        "AUROPHARMA": {"aliases": ["Aurobindo Pharma Ltd"]},
        "BOSCHLTD": {"aliases": ["Bosch Ltd"]},
        "PAGEIND": {"aliases": ["Page Industries Ltd"]},
        "TATAELXSI": {"aliases": ["Tata Elxsi Ltd"]},
        "NAUKRI": {"aliases": ["Info Edge India Ltd"]},
        "IGL": {"aliases": ["Indraprastha Gas Ltd"]},
        "JINDALSTEL": {"aliases": ["Jindal Steel & Power Ltd"]},
        "BALKRISIND": {"aliases": ["Balkrishna Industries Ltd"]},
        "MOTHERSON": {"aliases": ["Samvardhana Motherson International"]},
        "ACC": {"aliases": ["ACC Ltd"]},
        "GLAND": {"aliases": ["Gland Pharma Ltd"]},
        "UNITDSPR": {"aliases": ["United Spirits Ltd"]},
        "MARICO": {"aliases": ["Marico Ltd"]},
        "BIOCON": {"aliases": ["Biocon Ltd"]},
        "BANDHANBNK": {"aliases": ["Bandhan Bank Ltd"]},
        "IDFCFIRSTB": {"aliases": ["IDFC First Bank Ltd"]},
        "PNB": {"aliases": ["Punjab National Bank"]},
        "CANBK": {"aliases": ["Canara Bank"]},
        "TVSMOTOR": {"aliases": ["TVS Motor Company Ltd"]},
        "ASHOKLEY": {"aliases": ["Ashok Leyland Ltd"]},
        "BEL": {"aliases": ["Bharat Electronics Ltd"]},
        "TATACHEM": {"aliases": ["Tata Chemicals Ltd"]},
        "JUBLFOOD": {"aliases": ["Jubilant FoodWorks Ltd"]},
    },
    # Simplified risk themes for impactful news
    "risk_themes": {
        "financial": "(earnings OR revenue OR profit OR loss OR results OR quarterly OR guidance OR dividend)",
        "regulatory": "(regulation OR compliance OR fine OR penalty OR investigation OR SEBI OR RBI)",
        "operational": "(shutdown OR disruption OR strike OR recall OR outage OR supply chain)",
        "legal": "(lawsuit OR litigation OR court OR settlement OR arbitration)",
        "m&a": "(merger OR acquisition OR takeover OR buyout OR joint venture)",
    },
}
